channels: 64
n_classes: 1
lora_rank: 8
epochs: 100
batch_size: 32
lr: 0.0003
weight_decay: 0.0001
resize_to: 256
metric_threshold: 0.5
tversky_alpha: 0.3
tversky_beta: 0.7
main_weight: 1.0
aux2_weight: 0.6
aux3_weight: 0.4
save_every: 5
val_split_ratio_l4s: 0.1
prithvi_weights_root: /home/user/Desktop/Deep_learning_projects/4PI/prithvi_weights
